version: "3.9"
services:
  reurl:
    image: nekogravitycat/reurl:latest
    container_name: reurl
    restart: unless-stopped
    expose:
      - "5000"
    environment:
      - GUNICORN_CMD_ARGS="-b 0.0.0.0:5000"
    env_file:
      - ./.env/reurl.env
    volumes:
      - ./data:/app/data
  reurl-nginx:
    build: ./nginx
    container_name: reurl-nginx
    restart: unless-stopped
    expose:
      - 80
    depends_on:
      - reurl
  reurl-cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: reurl-cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file:
      - ./.env/cloudflared.env
    depends_on:
      - reurl-nginx
